name: Next Steps on Poll Pass

on:
  repository_dispatch:
    types: [testsavant_poll_passed]

jobs:
  continue:
    runs-on: ubuntu-latest
    steps:
      - name: Print payload
        run: |
          echo "Run ID: ${{ github.event.client_payload.run_id }}"
          echo "Results:"
          echo '${{ toJson(github.event.client_payload.result) }}'
      - name: Execute next workflow steps
        run: echo "Place deployment/tests steps here after gate passed via polling."
